// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htykqrmczqcokvmrsfui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eWtxcm1jenFjb2t2bXJzZnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTI3NDYsImV4cCI6MjA2NzAyODc0Nn0.LZLU8uQbQPv60ia05vtReIjJFiJGXFm-UJF2LQblbaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});